# Generated by Django 3.1.7 on 2021-07-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
