# Generated by Django 3.1.7 on 2021-07-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='name',
        ),
    ]
