# Generated by Django 3.1.7 on 2021-08-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_websitename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitename',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
