# Generated by Django 3.1.7 on 2021-08-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210806_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitename',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
