# Generated by Django 3.1.7 on 2021-08-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_tutorialsports'),
    ]

    operations = [
        migrations.CreateModel(
            name='sportsposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='tutorialssports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='images/')),
                ('icon', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='tutorialvideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('tutorial', models.CharField(max_length=200)),
                ('video_name', models.CharField(max_length=200)),
                ('video_src', models.CharField(max_length=200)),
            ],
        ),
    ]
