# Generated by Django 3.1.7 on 2021-08-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20210815_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitename',
            name='logo',
            field=models.FileField(upload_to='images/'),
        ),
    ]
