from django.urls import path,include
from . import views

urlpatterns = [
    path('edit',views.edit,name='edit'),
    path('',views.home,name='home'),
    path('tutorial',views.tutorial,name='tutorial'),
    path('knowledge',views.knowledge,name='knowledge'),
    path('tutorialvideo/<str:sports>/',views.tutorialvideo,name='tutorialvideo'),
    path('trainingHome',views.trainingHome,name='trainingHome'),
    path('football',views.football,name='football'),
    path('footballOverview',views.footballOverview,name='footballOverview'),
    path('footballParticipatingCountiries',views.footballParticipatingCountiries,name='footballParticipatingCountiries'),
    path('footballPlayingEnvironment',views.footballPlayingEnvironment,name='footballPlayingEnvironment'),
    path('footballEquipment',views.footballEquipment,name='footballEquipment'),
    path('footballPopularTerms',views.footballPopularTerms,name='footballPopularTerms'),
    path('footballPlayersAndPositions',views.footballPlayersAndPositions,name='footballPlayersAndPositions'),
    path('footballHowToPlay',views.footballHowToPlay,name='footballHowToPlay'),
    path('cricketOverview',views.cricketOverview,name='cricketOverview'),
    path('cricketBatAndBall',views.cricketBatAndBall,name='cricketBatAndBall'),
    path('cricketParticipatingCountries',views.cricketParticipatingCountries,name='cricketParticipatingCountries'),
    path('cricketPlayingEnvironment',views.cricketPlayingEnvironment,name='cricketPlayingEnvironment'),
    path('cricketEquipment',views.cricketEquipment,name='cricketEquipment'),
    path('PopularTermsinCricket',views.PopularTermsinCricket,name='PopularTermsinCricket'),
    path('howToPlayCricket',views.howToPlayCricket,name='howToPlayCricket'),
    path('cricketFormat',views.cricketFormat,name='cricketFormat'),
    
    path('videoTutorialHome',views.videoTutorialHome,name='videoTutorialHome'),
    path('tutorialHome',views.tutorialHome,name='tutorialHome'),
    path('login',views.login,name='login'),
    path('register',views.registe,name='register'),
    path('forgetPassword',views.forgetPassword, name='forgetPassword'),
    path('changepassword/<str:token>/',views.changepassword, name='changepassword'),
    path('updatelogo',views.updatelogo,name='updatelogo'),
    path('adminhome',views.adminhome,name="adminhome"),
    path('addfeatures',views.addfeatures,name='addfeatures'),
    path('updatefeatures',views.updatefeatures,name='updatefeatures'),
    path('deletefeatures',views.deletefeatures,name='deletefeatures'),
    path('addsocialmedia',views.addsocialmedia,name='addsocialmedia'),
    path('updatesocialmedia',views.updatesocialmedia,name='updatesocialmedia'),
    path('deletesocialmedia',views.deletesocialmedia,name='deletesocialmedia'),
    path('addvideo',views.addvideo, name='addvideo'),
]

